-- Niistal Cupertino Keybindings
-- macOS Mission Control, App Exposé, Control Center and Spotlight shortcuts

-- Unbind existing SUPER+UP and SUPER+DOWN (previously window focus)
hl.unbind("SUPER + UP")
hl.unbind("SUPER + DOWN")

-- Mission Control (macOS Spaces + All Windows overview)
o.bind("SUPER + UP", "Mission Control", "omarchy-shell shell call niistal.cupertino-overview openMissionControl")

-- App Exposé (All windows of current active application)
o.bind("SUPER + DOWN", "App Exposé", "omarchy-shell shell call niistal.cupertino-overview openAppExpose")

-- Control Center toggle
o.bind("SUPER + ALT + C", "Control Center", "omarchy-shell shell toggle niistal.cupertino-controlcenter")

-- Physical Lock Key (keyboard / laptop Lock button)
o.bind("XF86ScreenSaver", "Lock system", "omarchy-system-lock", { locked = true })

-- BEGIN mousemap
-- Mouse button bindings, generated by the MouseMap plugin.
-- Remove this block to disable them; the file it loads is regenerated
-- by the panel and is safe to delete.
pcall(dofile, os.getenv("HOME") .. "/.local/state/omarchy-mousemap/bindings.lua")
-- END mousemap
